name: Email Automation Processor

on:
  schedule:
    # Run every hour - automation will handle filtering based on analytics status
    - cron: '0 * * * *'
  workflow_dispatch: # Allow manual trigger for testing

jobs:
  process-scheduled-emails:
    runs-on: ubuntu-latest
    
    steps:
      - name: Process Scheduled Campaign Emails with Auto Warm-up
        run: |
          echo "🕐 Processing scheduled emails with warm-up at $(date)"
          
          # Process warm-up emails alongside campaign emails
          echo "🔥 Processing warm-up emails first..."
          warmup_response=$(curl -s -w "HTTPSTATUS:%{http_code}" \
            -X GET \
            -H "Content-Type: application/json" \
            "${{ secrets.APP_URL }}/api/automation/process-warmup?autoMode=true")
          
          warmup_code=$(echo $warmup_response | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
          warmup_body=$(echo $warmup_response | sed -e 's/HTTPSTATUS:.*//g')
          
          echo "🔥 Warm-up Status: $warmup_code"
          echo "🔥 Warm-up Response: $warmup_body"
          
          # Call the automation endpoint
          response=$(curl -s -w "HTTPSTATUS:%{http_code}" \
            -X GET \
            -H "Content-Type: application/json" \
            "${{ secrets.APP_URL }}/api/automation/process-scheduled?lookAhead=60&testMode=false&includeWarmup=true")
          
          # Extract HTTP status and body
          http_code=$(echo $response | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
          body=$(echo $response | sed -e 's/HTTPSTATUS:.*//g')
          
          # Log response
          echo "📊 HTTP Status: $http_code"
          echo "📧 Response: $body"
          
          # Check if successful
          if [ $http_code -eq 200 ]; then
            echo "✅ Email processing completed successfully"
            
            # Parse and log key metrics (if jq is available)
            if command -v jq &> /dev/null; then
              sent=$(echo "$body" | jq -r '.sent // 0')
              processed=$(echo "$body" | jq -r '.processed // 0')
              errors=$(echo "$body" | jq -r '.errors // 0')
              skipped=$(echo "$body" | jq -r '.skipped // 0')
              warmup_sent=$(echo "$warmup_body" | jq -r '.sent // 0')
              
              echo "📈 Summary: $sent campaign emails sent, $warmup_sent warm-up emails sent, $skipped skipped, $errors errors (total: $processed)"
              
              # Set job outputs for monitoring
              echo "sent=$sent" >> $GITHUB_OUTPUT
              echo "processed=$processed" >> $GITHUB_OUTPUT
              echo "errors=$errors" >> $GITHUB_OUTPUT
              echo "warmup_sent=$warmup_sent" >> $GITHUB_OUTPUT
            fi
          else
            echo "❌ Email processing failed with status $http_code"
            echo "Response: $body"
            exit 1
          fi

  process-warmup-scheduler:
    runs-on: ubuntu-latest
    # Run warming scheduler once per day at 9 AM UTC
    if: github.event.schedule == '0 9 * * *' || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Process Warmup Scheduler
        run: |
          echo "🌡️  Processing warmup scheduler at $(date)"
          
          response=$(curl -s -w "HTTPSTATUS:%{http_code}" \
            -X GET \
            -H "Content-Type: application/json" \
            "${{ secrets.APP_URL }}/api/warming/scheduler")
          
          http_code=$(echo $response | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
          body=$(echo $response | sed -e 's/HTTPSTATUS:.*//g')
          
          echo "📊 HTTP Status: $http_code"
          echo "🌡️  Response: $body"
          
          if [ $http_code -eq 200 ]; then
            echo "✅ Warmup scheduling completed successfully"
          else
            echo "❌ Warmup scheduling failed with status $http_code"
            exit 1
          fi

  process-warmup-execution:
    runs-on: ubuntu-latest
    # Run auto warmup execution once per day at 10 AM UTC (after scheduler)
    if: github.event.schedule == '0 10 * * *' || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Process Auto Warmup Execution
        run: |
          echo "🔥 Processing auto warmup execution at $(date)"
          
          response=$(curl -s -w "HTTPSTATUS:%{http_code}" \
            -X GET \
            -H "Content-Type: application/json" \
            "${{ secrets.APP_URL }}/api/automation/process-warmup?autoMode=true")
          
          http_code=$(echo $response | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
          body=$(echo $response | sed -e 's/HTTPSTATUS:.*//g')
          
          echo "📊 HTTP Status: $http_code"
          echo "🔥 Response: $body"
          
          if [ $http_code -eq 200 ]; then
            echo "✅ Auto warmup execution completed successfully"
            
            # Parse and log key metrics (if jq is available)
            if command -v jq &> /dev/null; then
              sent=$(echo "$body" | jq -r '.sent // 0')
              processed=$(echo "$body" | jq -r '.processed // 0')
              
              echo "🔥 Warmup Summary: $sent warm-up emails sent for $processed senders"
              
              # Set job outputs for monitoring
              echo "warmup_sent=$sent" >> $GITHUB_OUTPUT
              echo "warmup_processed=$processed" >> $GITHUB_OUTPUT
            fi
          else
            echo "❌ Auto warmup execution failed with status $http_code"
            echo "Response: $body"
            exit 1
          fi
 
 
